version: "3"

services:
  intervals:
    image: intervals:latest
    build:
      context: .
    working_dir: /var/app
    env_file: .env
    container_name: intervals
    networks:
      - app_net
    volumes:
      - ./app:/var/app/
    command:
      [
        "gunicorn",
        "app:create_app()",
        "-c/var/gunicorn.conf.py"
      ]
    ports:
      - "8000:8000"
networks:
  app_net:


