version: "3"

services:
  app:
    image: ${APP_NAME}:latest
    build:
      context: .
    working_dir: /var/app
    env_file: .env
    container_name: ${APP_NAME}
    restart: unless-stopped
    volumes:
      - ./app:/var/app/
    command: ["/var/app/init.sh"]
    ports:
      - "${APP_PORT}:${COMM_PORT}"
networks:
  default:
    name: ${APP_NAME}_net
